# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Punto1-A.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(561, 451)
        Dialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(False)
        self.title_window = QtWidgets.QLabel(Dialog)
        self.title_window.setGeometry(QtCore.QRect(34, 30, 491, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(20)
        self.title_window.setFont(font)
        self.title_window.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title_window.setAutoFillBackground(False)
        self.title_window.setAlignment(QtCore.Qt.AlignCenter)
        self.title_window.setObjectName("title_window")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 300, 211, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(230, 310, 310, 121))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/images/logo.png"))
        self.label_2.setObjectName("label_2")
        self.led_amarillo = QtWidgets.QPushButton(Dialog)
        self.led_amarillo.setGeometry(QtCore.QRect(120, 80, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.led_amarillo.setFont(font)
        self.led_amarillo.setStyleSheet("background-color: yellow; color: black")
        self.led_amarillo.setObjectName("led_amarillo")
        self.led_rojo = QtWidgets.QPushButton(Dialog)
        self.led_rojo.setGeometry(QtCore.QRect(290, 80, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.led_rojo.setFont(font)
        self.led_rojo.setStyleSheet("background-color: red; color: white")
        self.led_rojo.setObjectName("led_rojo")
        self.led_verde = QtWidgets.QSlider(Dialog)
        self.led_verde.setGeometry(QtCore.QRect(200, 180, 160, 22))
        self.led_verde.setMaximum(100)
        self.led_verde.setSingleStep(10)
        self.led_verde.setPageStep(20)
        self.led_verde.setSliderPosition(50)
        self.led_verde.setOrientation(QtCore.Qt.Horizontal)
        self.led_verde.setObjectName("led_verde")
        self.led_azul = QtWidgets.QSlider(Dialog)
        self.led_azul.setGeometry(QtCore.QRect(200, 230, 160, 22))
        self.led_azul.setMaximum(100)
        self.led_azul.setSingleStep(10)
        self.led_azul.setPageStep(20)
        self.led_azul.setSliderPosition(50)
        self.led_azul.setOrientation(QtCore.Qt.Horizontal)
        self.led_azul.setObjectName("led_azul")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(100, 180, 86, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(100, 230, 86, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Calculadora"))
        self.title_window.setText(_translate("Dialog", "Escritura de Puertos"))
        self.label.setText(_translate("Dialog", "Sebastián Camilo Ariza Rodríguez\n"
"Alejandro Melo\n"
"Yader Gamba Forero\n"
"Helmer Sierra Sierra"))
        self.led_amarillo.setText(_translate("Dialog", "Led amarillo"))
        self.led_rojo.setText(_translate("Dialog", "Led Rojo"))
        self.label_3.setText(_translate("Dialog", "Led verde"))
        self.label_4.setText(_translate("Dialog", "Led Azul"))
import logo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
