# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Punto1-B.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(561, 335)
        Dialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(False)
        self.title_window = QtWidgets.QLabel(Dialog)
        self.title_window.setGeometry(QtCore.QRect(34, 30, 491, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(20)
        self.title_window.setFont(font)
        self.title_window.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title_window.setAutoFillBackground(False)
        self.title_window.setAlignment(QtCore.Qt.AlignCenter)
        self.title_window.setObjectName("title_window")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 170, 211, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(230, 180, 310, 121))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/images/logo.png"))
        self.label_2.setObjectName("label_2")
        self.posicion = QtWidgets.QSlider(Dialog)
        self.posicion.setGeometry(QtCore.QRect(230, 80, 160, 22))
        self.posicion.setMaximum(180)
        self.posicion.setSingleStep(5)
        self.posicion.setPageStep(5)
        self.posicion.setProperty("value", 90)
        self.posicion.setSliderPosition(90)
        self.posicion.setOrientation(QtCore.Qt.Horizontal)
        self.posicion.setObjectName("posicion")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 80, 159, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(40, 120, 181, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(230, 120, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Calculadora"))
        self.title_window.setText(_translate("Dialog", "Escritura de Puertos"))
        self.label.setText(_translate("Dialog", "Sebastián Camilo Ariza Rodríguez\n"
"Alejandro Melo\n"
"Yader Gamba Forero\n"
"Helmer Sierra Sierra"))
        self.label_3.setText(_translate("Dialog", "Posición del Servo"))
        self.label_4.setText(_translate("Dialog", "Selección del Servo"))
import logo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
