# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Punto4-B.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTimer
from time import sleep

import RPi.GPIO as GPIO #Importación de los pines GPIO
from time import sleep # Importación del módulo sleep para hacer delays

GPIO.setmode(GPIO.BCM)

pulsador = 17
GPIO.setup(pulsador, GPIO.IN)

styleHigh = '''
QWidget {
    background-color: red;
    color: white;
}       

QPushButton {
    background-color: red;
    color: white;

    border-radius: 35px;        
    border-width: 1px;
    border-style: solid;
}

'''

styleLow = '''
QWidget {
    background-color: blue;
    color: white;
}       

QPushButton {
    background-color: blue;
    color: white;

    border-radius: 35px;        
    border-width: 1px;
    border-style: solid;
}

'''

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(561, 381)
        Dialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(False)
        self.title_window = QtWidgets.QLabel(Dialog)
        self.title_window.setGeometry(QtCore.QRect(34, 30, 491, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(20)
        self.title_window.setFont(font)
        self.title_window.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title_window.setAutoFillBackground(False)
        self.title_window.setAlignment(QtCore.Qt.AlignCenter)
        self.title_window.setObjectName("title_window")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 220, 211, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(230, 230, 310, 121))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/images/logo.png"))
        self.label_2.setObjectName("label_2")
        self.estado_pulsador = QtWidgets.QLabel(Dialog)
        self.estado_pulsador.setGeometry(QtCore.QRect(210, 100, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.estado_pulsador.setFont(font)
        self.estado_pulsador.setStyleSheet(styleLow)
        self.estado_pulsador.setAlignment(QtCore.Qt.AlignCenter)
        self.estado_pulsador.setObjectName("estado_pulsador")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Calculadora"))
        self.title_window.setText(_translate("Dialog", "Escritura de Puertos"))
        self.label.setText(_translate("Dialog", "Sebastián Camilo Ariza Rodríguez\n"
"Alejandro Melo\n"
"Yader Gamba Forero\n"
"Helmer Sierra Sierra"))
        self.estado_pulsador.setText(_translate("Dialog", "Bajo"))

import logo_rc

def cambiar_estilo():
    # Comprueba el estilo actual y cambia al otro
    global pulsador
    if GPIO.input(pulsador) == 0:
        ui.estado_pulsador.setText("Bajo")
        ui.estado_pulsador.setStyleSheet(styleLow)
    else:
        ui.estado_pulsador.setText("Alto")
        ui.estado_pulsador.setStyleSheet(styleHigh)
    
    # No es necesario llamar a repaint() aquí ya que setStyleSheet ya solicita una actualización de la UI

# Crea un QTimer
timer = QTimer()
timer.timeout.connect(cambiar_estilo)  # Conecta el temporizador a la función cambiar_estilo
timer.start(1000)  # Establece el temporizador para que se ejecute cada 1000 milisegundos (1 segundo)

def Ejecutar():
    ui.estado_pulsador.setStyleSheet(styleHigh)  # Establece el estilo inicial
    Dialog.show()
    timer.start()  # Inicia el temporizador si aún no está corriendo

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Ejecutar()
    sys.exit(app.exec_())
