# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Punto5-B.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import RPi.GPIO as GPIO #Importación de los pines GPIO
from time import sleep # Importación del módulo sleep para hacer delays

GPIO.setmode(GPIO.BCM)

pins = [17, 27, 22, 5]
GPIO.setup(pins, GPIO.OUT, initial=GPIO.LOW)

secuencia = [
    [1,0,0,0],
    [0,1,0,0],
    [0,0,1,0],
    [0,0,0,1]
]

secuencia_invertida = [
    [0,0,0,1],
    [0,0,1,0],
    [0,1,0,0],
    [1,0,0,0]
]

#Se mueve 0.7 por cada secuencia
def vueltasaSecuencias(vueltas):
    grados = vueltas * 360
    secuencias = int(grados / 0.7)
    return secuencias


styleButton = '''
QWidget {
    background-color: green;
}       

QPushButton {
    background-color: green;
    color: white;

    border-radius: 35px;        
    border-width: 1px;
    border-style: solid;
}

'''

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(561, 451)
        Dialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(False)
        self.title_window = QtWidgets.QLabel(Dialog)
        self.title_window.setGeometry(QtCore.QRect(34, 30, 491, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(20)
        self.title_window.setFont(font)
        self.title_window.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title_window.setAutoFillBackground(False)
        self.title_window.setAlignment(QtCore.Qt.AlignCenter)
        self.title_window.setObjectName("title_window")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 300, 211, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(230, 310, 310, 121))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/images/logo.png"))
        self.label_2.setObjectName("label_2")
        self.arrancar = QtWidgets.QPushButton(Dialog)
        self.arrancar.setGeometry(QtCore.QRect(220, 210, 161, 61))
        self.arrancar.setStyleSheet(styleButton)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.arrancar.setFont(font)
        self.arrancar.setStyleSheet("background-color: green; color: white")
        self.arrancar.setObjectName("arrancar")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(60, 100, 151, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.vueltas = QtWidgets.QTextEdit(Dialog)
        self.vueltas.setGeometry(QtCore.QRect(220, 100, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.vueltas.setFont(font)
        self.vueltas.setObjectName("vueltas")
        self.sentido = QtWidgets.QComboBox(Dialog)
        self.sentido.setGeometry(QtCore.QRect(220, 150, 161, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.sentido.setFont(font)
        self.sentido.setObjectName("sentido")
        self.sentido.addItem("")
        self.sentido.addItem("")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(60, 150, 151, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.arrancar.clicked.connect(self.Arrancar)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Motor paso a Paso"))
        self.title_window.setText(_translate("Dialog", "Motor paso a paso"))
        self.label.setText(_translate("Dialog", "Sebastián Camilo Ariza Rodríguez\n"
"Alejandro Melo\n"
"Yader Gamba Forero\n"
"Helmer Sierra Sierra"))
        self.arrancar.setText(_translate("Dialog", "¡GO!"))
        self.label_3.setText(_translate("Dialog", "Cantidad de vueltas"))
        self.vueltas.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p></body></html>"))
        self.sentido.setItemText(0, _translate("Dialog", "Horario"))
        self.sentido.setItemText(1, _translate("Dialog", "Antihorario"))
        self.label_4.setText(_translate("Dialog", "Sentido de giro:"))

    def Arrancar(self):
        if self.sentido.currentText() == "Horario":
            try:
                vueltas = float(self.vueltas.toPlainText())
            except:
                vueltas = 0
            for i in range(vueltasaSecuencias(vueltas)):
                for paso in secuencia:
                    for pin, valor in zip(pins, paso):
                        GPIO.output(pin, valor)
                        sleep(0.001)
        elif self.sentido.currentText() == "Antihorario":
            try:
                vueltas = float(self.vueltas.toPlainText())
            except:
                vueltas = 0
            for i in range(vueltasaSecuencias(vueltas)):
                for paso in secuencia_invertida:
                    for pin, valor in zip(pins, paso):
                        GPIO.output(pin, valor)
                        sleep(0.001)

import logo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
